import Head from 'next/head'
import Image from 'next/image'
import Nav from '@/components/nav'
import Requests from '@/components/requests'
import Script from 'next/script'

export default function Home() {
	return (
		<>
		<Head>
		<title>The High Table</title>
		<meta name="description" content="Generated by create next app" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="icon" href="/favicon.ico" />
		</Head>
		<div className="bg-white dark:bg-neutral-800 min-h-screen">
			<header className="bg-white dark:bg-neutral-900">
				<Nav/>
			</header>
			<main className="bg-white dark:bg-neutral-800">
				<div className="container mx-auto grid grid-cols-7 mt-8 ">
					<Requests/>
				</div>
			</main>
		</div>
		</>
	)
}
